config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => :registrations }
  root to: 'pages#home'
  get '/devteam', to: "pages#devteam"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :bids, only: [:create , :update ]
    resources :reviews, only: [ :new, :create ]
  end

  resources :users, only: [:show, :edit, :update]
  get "users/:id/dashboard", to: "users#dashboard", as: :dashboard

  resources :chatrooms, only: [:show] do
    resources :messages, only: :create
  end

resources :bids, only: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :bids, dependent: :destroy
  has_many :reviews, through: :posts, dependent: :destroy
  has_one_attached :photo

  has_many :host_chatrooms, :class_name => 'Chatroom', :foreign_key => 'host_id'
  has_many :guest_chatrooms, :class_name => 'Chatroom', :foreign_key => 'guest_id'
  # has_many :messages

  def average_rating
    stars = []
    bids.where(approved: true).each do |bid|
          unless bid.reviews.first.nil?
            stars << bid.reviews.first.rating
          end
    end
    average = stars.sum.to_f / stars.size
    if average.nan?
      return 0
    else
      average
    end
  end

  def total_rating
    stars = []
    bids.where(approved: true).each do |bid|
          unless bid.reviews.first.nil?
            stars << bid.reviews.first.rating
          end
    end
    average = stars.sum

  end

  def render_stars(value)
      output = ''
      if (1..5).include?(value.floor)
        value.floor.times { output  += '<i class="fas fa-star"></i>'}
      end
      if value == (value.floor + 0.5) && value.to_i != 5
        output  += '<i class="fas fa-star-half"></i>'
      end
      output.html_safe
  end

  def score
    score = bids.joins(:post).where(approved: true, posts: { completed: true}).count
    score* 10 + total_rating
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    authorize @user
    @posts = @user.posts
    @bids = @user.bids
    @stars = if avg_stars.nan?
      ""
    else
      render_stars(avg_stars)
    end
  end

  def dashboard
    @user = User.find(params[:id])
    authorize @user
    @posts = @user.posts
    @bids = @user.bids
    @reviews = @user.reviews
    @top_users = User.all.sort { |user1, user2| user2.score <=> user1.score }.first(5)
  end

  private

  def avg_stars
    stars = []
    @user.bids.where(approved: true).each do |bid|
          unless bid.reviews.first.nil?
            stars << bid.reviews.first.rating
          end
    end
    stars.inject{ |sum, el| sum + el }.to_f / stars.size

  end

  def render_stars(value)
      output = ''
      if (1..5).include?(value.floor)
        value.floor.times { output  += '<i class="fas fa-star"></i>'}
      end
      if value == (value.floor + 0.5) && value.to_i != 5
        output  += '<i class="fas fa-star-half"></i>'
      end
      output.html_safe
  end
end

app/views/users/dashboard.html.erb
<% if policy(@user).dashboard? %>
  <div class="container">
    <div class="dashboard-container">
      <h2 class="margin-bottom header">My Dashboard</h2>
      <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
          <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">My Help Requests</a>
        </li>
        <li class="nav-item" role="presentation">
          <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">My Offers to Help</a>
        </li>
      </ul>
      <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
          <div class="post-container">
            <h6 class="sub-header-blue">Pending, waiting for someone to offer help</h6>
            <% @posts.where(completed: false).each do |post| %>
              <% if post.bids.empty? %>
                <%= link_to post_path(post), class: "links" do %>
                  <div class="post">
                    <div class="avatar-post-container">
                      <div>
                        <% if  post.user.photo.attached? %>
                          <%= cl_image_tag post.user.photo.key,height: 72, :quality=>60, crop: :mfit, class: "avatar-extra-large", alt: "profile image"  %>
                        <% else %>
                          <%= cl_image_tag("fpatfvf9edoaaqhbkfrt",
                                width: 72, crop: :fill, class: "avatar-extra-large", alt: "profile image")  %>
                        <% end %>
                      </div>
                      <div class="post-content">
                        <h3><%= post.title %></h3>
                        <p style="overflow: hidden; text-overflow: ellipsis;"><%= truncate(post.content, length: 119) %></p>
                      </div>
                    </div>
                    <div class="date-btn">

                      <p><strong><%= post.date.nil? ? "ASAP" : post.date.strftime("%d %b %Y") %></strong></p>
                    </div>
                  </div>
                <% end %>
              <% end %>
            <% end %>

            <h6 class="sub-header-purple">Ready for approval</h6>
            <% @posts.where(completed: false).each do |post| %>
              <% unless post.bids.empty? || post.bids.any? { |bid| bid.approved } %>
                <%= link_to post_path(post), class: "links" do %>
                  <div class="post">
                    <div class="avatar-post-container">
                      <div>
                        <% if  post.user.photo.attached? %>
                          <%= cl_image_tag post.user.photo.key,height: 72, :quality=>60, crop: :mfit, class: "avatar-extra-large", alt: "profile image"  %>
                        <% else %>
                          <%= cl_image_tag("fpatfvf9edoaaqhbkfrt",
                                width: 72, crop: :fill, class: "avatar-extra-large", alt: "profile image")  %>
                        <% end %>
                      </div>
                      <div class="post-content">
                        <h3><%= post.title %></h3>
                        <p style="overflow: hidden; text-overflow: ellipsis;"><%= truncate(post.content, length: 119) %></p>
                      </div>
                    </div>
                    <div class="date-btn">
                      <p><strong><%= post.date.nil? ? "ASAP" : post.date.strftime("%d %b %Y") %></strong></p>
                    </div>
                  </div>
                <% end %>
              <% end %>
            <% end %>

            <h6 class="sub-header-green">Approved, waiting to be completed</h6>
            <% @posts.where(completed: false).each do |post| %>
              <% if post.bids.any? { |bid| bid.approved } %>
                <%= link_to post_path(post), class: "links" do %>
                  <div class="post">
                    <div class="avatar-post-container">
                      <div>
                        <% if  post.user.photo.attached? %>
                          <%= cl_image_tag post.user.photo.key,height: 72, :quality=>60, crop: :mfit, class: "avatar-extra-large", alt: "profile image"  %>
                        <% else %>
                          <%= cl_image_tag("fpatfvf9edoaaqhbkfrt",
                                width: 72, crop: :fill, class: "avatar-extra-large", alt: "profile image")  %>
                        <% end %>
                      </div>
                      <div class="post-content">
                        <h3><%= post.title %></h3>
                        <p style="overflow: hidden; text-overflow: ellipsis;"><%= truncate(post.content, length: 119) %></p>
                      </div>
                    </div>
                    <div class="date-btn">
                      <p><strong><%= post.date.nil? ? "ASAP" : post.date.strftime("%d %b %Y") %></strong></p>
                    </div>
                  </div>
                <% end %>
              <% end %>
            <% end %>

            <h6 class="sub-header">Completed</h6>
            <% @posts.where(completed: true).each do |post| %>
              <%= link_to post_path(post), class: "links" do %>
                <div class="post">
                  <div class="avatar-post-container">
                    <div>
                      <% if  post.user.photo.attached? %>
                        <%= cl_image_tag post.user.photo.key,height: 72, :quality=>60, crop: :mfit, class: "avatar-extra-large", alt: "profile image"  %>
                      <% else %>
                        <%= cl_image_tag("fpatfvf9edoaaqhbkfrt",
                              width: 72, crop: :fill, class: "avatar-extra-large", alt: "profile image")  %>
                      <% end %>
                    </div>
                    <div class="post-content">
                      <h3><%= post.title %></h3>
                      <p style="overflow: hidden; text-overflow: ellipsis;"><%= truncate(post.content, length: 119) %></p>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
          <div class="post-container">
            <h6 class="sub-header-blue">Pending offers, waiting for offer to be accepted</h6>
            <% @bids.where(approved: false).each do |bid| %>

              <% unless bid.post.bids.any? {|bid| bid.approved} %>
                <%= link_to post_path(bid.post), class: "links" do %>
                      <div class="post">
                        <div class="avatar-post-container">
                          <div>
                            <% if  bid.post.user.photo.attached? %>
                              <%= cl_image_tag bid.post.user.photo.key,height: 72, :quality=>60, crop: :mfit, class: "avatar-extra-large", alt: "profile image"  %>
                            <% else %>
                              <%= cl_image_tag("fpatfvf9edoaaqhbkfrt",
                                    width: 72, crop: :fill, class: "avatar-extra-large", alt: "profile image")  %>
                            <% end %>
                          </div>
                          <div class="post-content">
                            <h3><%= bid.post.title %></h3>
                            <p style="overflow: hidden; text-overflow: ellipsis;"><%= truncate(bid.post.content, length: 119) %></p>
                          </div>
                        </div>
                        <div class="date-btn">
                          <p><strong><%= bid.post.date.nil? ? "ASAP" : bid.post.date.strftime("%d %b %Y") %></strong></p>
                        </div>
                      </div>
                  <% end %>
                <% end %>
              <% end %>

            <h6 class="sub-header-green">Approved offers, waiting to be completed</h6>
            <% @bids.where(approved: true).each do |bid| %>
              <%= link_to post_path(bid.post), class: "links" do %>
                <% unless bid.post.completed %>
                    <div class="post">
                      <div class="avatar-post-container">
                        <div>
                          <% if  bid.post.user.photo.attached? %>
                            <%= cl_image_tag bid.post.user.photo.key,height: 72, :quality=>60, crop: :mfit, class: "avatar-extra-large", alt: "profile image"  %>
                          <% else %>
                            <%= cl_image_tag("fpatfvf9edoaaqhbkfrt",
                                  width: 72, crop: :fill, class: "avatar-extra-large", alt: "profile image")  %>
                          <% end %>
                        </div>
                        <div class="post-content">
                          <h3><%= bid.post.title %></h3>
                          <p style="overflow: hidden; text-overflow: ellipsis;"><%= truncate(bid.post.content, length: 119) %></p>
                        </div>
                      </div>
                      <div class="date-btn">
                        <p><strong><%= bid.post.date.nil? ? "ASAP" : bid.post.date.strftime("%d %b %Y") %></strong></p>
                      </div>
                    </div>
                  <% end %>
                <% end %>
              <% end %>

              <h6 class="sub-header">Completed offers</h6>
              <% @bids.where(approved: true).each do |bid| %>
                  <% if bid.post.completed %>

                      <div class="post">
                        <div class="avatar-post-container">
                          <%= link_to post_path(bid.post), class: "links d-flex" do %>
                            <div>
                              <% if  bid.post.user.photo.attached? %>
                                <%= cl_image_tag bid.post.user.photo.key,height: 72, :quality=>60, crop: :mfit, class: "avatar-extra-large", alt: "profile image"  %>
                              <% else %>
                                <%= cl_image_tag("fpatfvf9edoaaqhbkfrt",
                                      width: 72, crop: :fill, class: "avatar-extra-large", alt: "profile image")  %>
                              <% end %>
                            </div>
                            <div class="post-content">
                              <h3><%= bid.post.title %></h3>
                              <p><%= bid.post.content %></p>
                            </div>
                          <% end %>
                        </div>
                        <% if bid.reviews.select{ |review| review.user_id == current_user.id }.empty? %>
                          <div class="review-btn links">
                            <%= link_to "Review", new_post_review_path(bid.post) %>
                          </div>
                        <% end %>
                      </div>
                    <% end %>
                  <% end %>

          </div>
        </div>
      </div>
    </div>
    <div class="top-helpr-container col-5">
      <h2 class="margin-bottom header">Top Helpr's</h2>

      <% @top_users.first(3).each do |user| %>
        <%= link_to user_path(user), class: "links" do %>
          <div class="top-helpr-card">
            <div class="avatar-post-container">
              <div>
                  <% if  user.photo.attached? %>
                    <%= cl_image_tag user.photo.key, height: 56, :quality=>60, crop: :mfit, class: "avatar-large", alt: "profile image"  %>
                  <% else %>
                  <%= cl_image_tag("fpatfvf9edoaaqhbkfrt",
                        width: 56, crop: :fill, class: "avatar-large", alt: "profile image")  %>
                <% end %>
              </div>
              <div class="top-helpr-content">
                <h3><%= user.first_name %> <%= user.last_name %></h3>
                <span><%= user.render_stars(user.average_rating) %></span>
              </div>
            </div>
            <div class="d-flex align-items-center justify-content-center">
              <% if user == @top_users[0] %>
                <div class="points mr-3">
                  <h4><%= user.score %></h4>
                  <p>Helpr Points</p>
                </div>
                <%= image_tag "gold.png", alt: "gold trophy", width: 60, class: "trophy" %>
              <% elsif user == @top_users[1] %>
                  <div class="points mr-3">
                    <h4><%= user.score %></h4>
                    <p>Helpr Points</p>
                  </div>
                <%= image_tag "silver.png", alt: "silver trophy", width: 60, class: "trophy" %>
              <% elsif user == @top_users[2] %>
                  <div class="points mr-3">
                    <h4><%= user.score %></h4>
                    <p>Helpr Points</p>
                  </div>
                <%= image_tag "bronze.png", alt: "bronze trophy", width: 60, class: "trophy" %>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>

    </div>
  </div>

<% end %>

app/views/users/show.html.erb
<br>
<div class="container-narrow mb-3 mt-3">
  <div class="user-info" >
    <br>
    <% if  @user.photo.attached? %>
    <%= cl_image_tag @user.photo.key,height: 150, :quality=>60, crop: :mfit, class: "avatar-show-square", alt: "profile image"  %>
    <% else %>
    <div class="avatar-show-square">
    <%= cl_image_tag("fpatfvf9edoaaqhbkfrt", width: 150, crop: :fill, class: "avatar-show-square", alt: "profile image")  %>
    </div>
    <% end %>
    <div class="info">
      <h2><%= @user.first_name %> <%= @user.last_name %></h2>
      <span class="d-flex"><%= @stars %> <h3 class="helpr-points ml-2"><%= @user.score %> helpr points</h3></span>
      <p><%= @user.bio %></p>
    <div class="address-align"><%= image_tag "unitedkingdom.png", class: "unitedkingdom", alt: "unitedkingdom.png", height: 35 %> <a class="address"><%= current_user == @user ? @user.address : @user.address.gsub(/^.../, '***') %></a></div>
      <br>
    </div>
  </div>
<hr>

  <% if user_signed_in? && @user == current_user %>
  <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-profile-edit" %>
  <%= link_to "Get Help", new_post_path, class: "btn btn-profile-post" %>
  <% end %>

<div class="reviews">
  <% if user_signed_in? && @user == current_user %>
  <h2 class="header">My Reviews</h2>
  <% else %>
  <h2 class="header">Reviews</h2>
  <% end %>
  <% if @bids.where(approved: true).map(&:reviews).flatten.any? %>
    <% @bids.where(approved: true).each do |bid| %>
      <% if bid.reviews.any?%>
        <div class="review-post">
          <div class="avatar-post-container">
            <div>
              <% review = bid.reviews.first%>
              <% if  review.user.photo.attached? %>
                <%= cl_image_tag review.user.photo.key,height: 72, :quality=>60, crop: :mfit, class: "avatar-extra-large", alt: "profile image"  %>
              <% else %>
                <%= cl_image_tag("fpatfvf9edoaaqhbkfrt",
                      width: 72, crop: :fill, class: "avatar-extra-large", alt: "profile image")  %>
              <% end %>

            </div>
            <div class="post-content">
              <h3><%= review.user.first_name %> <%= review.user.last_name %></h3>
              <p><%= review.content %></p>
              <p><%= '<i class="fas fa-star"></i>'.html_safe * review.rating %></p>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  <% elsif @posts.map(&:reviews).flatten.reject { |review| review.user_id == @user.id }.any? %>
      <% @posts.map(&:reviews).flatten.reject { |review| review.user_id == @user.id }.each do |review| %>
    <div class="review-post">
      <div class="avatar-post-container">
        <div>
          <% if  review.user.photo.attached? %>
            <%= cl_image_tag review.user.photo.key,height: 72, :quality=>60, crop: :mfit, class: "avatar-extra-large", alt: "profile image"  %>
          <% else %>
            <%= cl_image_tag("fpatfvf9edoaaqhbkfrt",
                  width: 72, crop: :fill, class: "avatar-extra-large", alt: "profile image")  %>
          <% end %>

        </div>
        <div class="post-content">
          <h3><%= review.user.first_name %> <%= review.user.last_name %></h3>
          <p><%= review.content %></p>
          <p><%= '<i class="fas fa-star"></i>'.html_safe * review.rating %></p>
        </div>
      </div>
    </div>
  <% end %>
  <% else %>
    <p> No reviews yet </p>
    <hr>
  <%= link_to "Community Feed", posts_path, class: "btn btn-profile-post" %>
  <% end %>
  </div>
</div>
<br>