config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => :registrations }
  root to: 'pages#home'
  get '/devteam', to: "pages#devteam"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :bids, only: [:create , :update ]
    resources :reviews, only: [ :new, :create ]
  end

  resources :users, only: [:show, :edit, :update]
  get "users/:id/dashboard", to: "users#dashboard", as: :dashboard

  resources :chatrooms, only: [:show] do
    resources :messages, only: :create
  end

resources :bids, only: :destroy

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<!--
<script>
  const hideMessage = () => {
    const message = document.querySelector(".alert");
    message.style.display = "none";
  }
  setTimeout(function () {
    hideMessage();
  }, 4000);
</script>

 -->

app/views/shared/_footer.html.erb
 <!-- Footer -->
<footer class="page-footer font-small special-color-dark pt-4">

  <!-- Footer Elements -->
  <div class="footer-container">

    <!-- Social buttons -->
    <ul class="list-unstyled list-inline text-center">
      <li class="list-inline-item">
        <a target="_blank", href="https://www.facebook.com", class="btn-floating btn-fb mx-1">
          <i class="fab fa-facebook-f"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a target="_blank", href="https://twitter.com/CommunityHelpr", class="btn-floating btn-tw mx-1">
          <i class="fab fa-twitter"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a target="_blank", href="https://www.youtube.com", class="btn-floating btn-gplus mx-1">
          <i class="fab fa-youtube"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a target="_blank", href="https://www.snapchat.com", class="btn-floating btn-li mx-1">
          <i class="fab fa-snapchat"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a target="_blank", href="https://www.instagram.com/helprcommunity/", class="btn-floating btn-dribbble mx-1">
          <i class="fab fa-instagram"> </i>
        </a>
      </li>
    </ul>
    <!-- Social buttons -->

  </div>
  <!-- Footer Elements -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Helpr | info@helpr.com | +44 21657 8943 | <%= link_to 'Meet the Team', devteam_path, class: "devlink" %>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

app/views/shared/_navbar-in-app.html.erb
<div class="sticky navbar navbar-expand-sm navbar-light navbar-lewagon navbar-helpr <%= "navbar-home" if params[:action] == "home" %>">

  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "helpr-white.png", style: "width: 100px" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item ">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
        <li class="nav-item">
          <%= link_to "Community Feed", posts_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Dashboard", dashboard_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Profile", user_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <% if  current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key,height: 40, :quality=>60, crop: :mfit, class: "avatar dropdown-toggle", alt: "profile image", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
          <% else %>
            <%= cl_image_tag("fpatfvf9edoaaqhbkfrt",
                  width: 40, crop: :fill, class: "avatar", alt: "profile image", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  )  %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="sticky navbar navbar-expand-sm navbar-light navbar-lewagon navbar-helpr mb-1 <%= "navbar-home" if params[:action] == "home" %>">

  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "helpr-white.png", style: "width: 100px" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item ">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
        <li class="nav-item">
          <%= link_to "Community Feed", posts_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Dashboard", dashboard_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Profile", user_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <% if  current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key,height: 40, :quality=>60, crop: :mfit, class: "avatar dropdown-toggle", alt: "profile image", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
          <% else %>
            <%= cl_image_tag("fpatfvf9edoaaqhbkfrt",
                  width: 40, crop: :fill, class: "avatar", alt: "profile image", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  )  %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>