config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => :registrations }
  root to: 'pages#home'
  get '/devteam', to: "pages#devteam"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :bids, only: [:create , :update ]
    resources :reviews, only: [ :new, :create ]
  end

  resources :users, only: [:show, :edit, :update]
  get "users/:id/dashboard", to: "users#dashboard", as: :dashboard

  resources :chatrooms, only: [:show] do
    resources :messages, only: :create
  end

resources :bids, only: :destroy

end

app/models/post.rb
class Post < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  belongs_to :user
  has_many :bids, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_one :chatroom, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  before_validation :set_address
  private
  def set_address
    self.address = self.user.address
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = policy_scope(Post).geocoded.order(created_at: :desc)
    @live_posts = @posts.reject { |post| post.completed || post.bids.any? { |bid| bid.approved }}


    @markers = @live_posts.map do |post|
      {
        lat: post.latitude,
        lng: post.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { post: post }),
        image_url: helpers.asset_url('helpr-bubble.png')

      }
    end
  end

  def show
    @post = Post.find(params[:id])
    authorize @post
    @user = @post.user
    if current_user == @post.user || current_user == @post.bids.find_by(approved: true).try(:user)
      @chatroom = Chatroom.find_by(post: @post)
    end
    @message = Message.new
  end

  def new
    @post = Post.new
    authorize @post
  end

  def create
    @post = Post.new(post_params)
    authorize @post
    @post.user = current_user
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    authorize @post
  end

  def update
    @post = Post.find(params[:id])
    authorize @post
    if params[:completed] == "true"
      @post.completed = true
      @post.save
      redirect_to new_post_review_path(@post), notice: "post marked as completed"
    elsif @post.update(post_params)
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    authorize @post
    @post.destroy
    redirect_to posts_path
  end

    private

    def post_params
      params.require(:post).permit(:title, :content, :date)
    end
end

app/views/posts/_info_window.html.erb
<%= link_to post_path(post), class: "links" do %>
  <div>
    <% if  post.user.photo.attached? %>
      <%= cl_image_tag post.user.photo.key,height: 40, :quality=>60, crop: :mfit, class: "avatar", alt: "profile image"  %>
    <% else %>
      <%= cl_image_tag("fpatfvf9edoaaqhbkfrt",
            width: 20, crop: :fill, class: "avatar", alt: "profile image")  %>
    <% end %>
  </div>
  <div>
    <h3><%= post.title %></h3>
    <p><%= post.content %></p>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container mt-2 mb-4">
  <div class="row justify-content-center w-100 mb-3 mt-3">
    <div class="col-6">
      <div style="text-align: center;">
        <h4> Edit your post for </h4>
        <h3> <%= @post.title %> </h3>
      </div>
          <br>
          <hr>
          <br>

           <%= simple_form_for(@post) do |f| %>
           <%= f.error_notification %>
           <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

          <div class="form-inputs">
            <%= f.input :title %>
            <%= f.input :content %>
            <%= f.input :date, as: :string %>
          </div>
          <br>

          <div class="form-actions">
             <%= f.submit "Update", class: "btn btn-profile-post" %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">

  <div class="posts-container">
    <% if policy(Post).create? %>
      <%= link_to new_post_path, class: "links" do %>
        <div class="create-post">
          <% if  current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key,height: 40, :quality=>60, crop: :mfit, class: "avatar", alt: "profile image"  %>
          <% else %>
            <%= cl_image_tag("fpatfvf9edoaaqhbkfrt",
                  width: 40, crop: :fill, class: "avatar", alt: "profile image")  %>
          <% end %>
          <p><strong>Need Help?</strong> Post a request.</p>
        </div>
      <% end %>
    <% end %>
    <div class="post-container">

      <% @posts.each do |post| %>

        <% unless post.completed || post.bids.any? { |bid| bid.approved } %>
          <%= link_to post_path(post), class: "links" do %>
            <div class="post">
              <div class="avatar-post-container">
                <div>
                  <% if  post.user.photo.attached? %>
                    <%= cl_image_tag post.user.photo.key,height: 72, :quality=>60, crop: :mfit, class: "avatar-extra-large", alt: "profile image"  %>
                  <% else %>
                    <%= cl_image_tag("fpatfvf9edoaaqhbkfrt",
                          width: 72, crop: :fill, class: "avatar-extra-large", alt: "profile image")  %>
                  <% end %>
                </div>
                <div class="post-content">
                  <h3><%= post.title %></h3>
                  <p style="overflow: hidden; text-overflow: ellipsis;"><%= truncate(post.content, length: 119) %></p>
                </div>
              </div>
              <div class="date-btn">
                <p><strong><%= post.date.nil? ? "ASAP" : post.date.strftime("%d %b %Y") %></strong></p>
              </div>
            </div>
          <% end %>
        <% end %>

      <% end %>
    </div>
  </div>

  <div class="map-container map-posts-index ">
    <div id="map"
         style="width: 100%; height: 500px;"
         data-markers="<%= @markers.to_json %>"
         data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    <div class="map-bottom">
      <h3>Help map</h3>
      <p>See all the help requests in your area on the help map.</p>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="card-img-to-left">
  <div class="card-img">
    <img alt="volunteers4" src="/assets/volunteers4.png">
  </div>

  <div class="form-container">
  <div class="card-img-to-right">
  <!--   <div class="container mt-2 mb-4">
      <div class="row justify-content-center w-100 mb-3 mt-3"> -->
          <div class="title text-center">
            <h2>Hello there !</h2>
            <h6>Your post will soon be visible to the largest community of volunteers</h6>
          </div>

          <br>
          <hr>
          <br>

           <%= simple_form_for(@post) do |f| %>
           <%= f.error_notification %>
           <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

          <div class="form-inputs">
            <%= f.input :title %>
            <%= f.input :content %>
            <%= f.input :date, as: :string %>
          </div>
          <br>

          <div class="form-actions">
            <%= f.button :submit, "Get Help", class: "btn btn-profile-post" %>
          </div>
        <% end %>
    </div>
  </div>
</div>
</div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="show-post-container">
    <div>
        <div class="img-text">
          <div class ="linkto">
            <% if  @post.user.photo.attached? %>
              <%= cl_image_tag @post.user.photo.key,height: 150, :quality=>60, crop: :mfit, class: "avatar-show-square", alt: "profile image" %>
            <% else %>
              <%= cl_image_tag("fpatfvf9edoaaqhbkfrt", width: 150, crop: :fill, class: "avatar-show-square", alt: "profile image") %>
              <%= link_to 'View Profile' , user_path(@user), class: "textalignprofile"  %>
            <% end %>
          </div>
          <div class="show-text">
            <div class="d-flex justify-content-between name-date-container">
              <div class="d-flex">
                <h3><%= @post.user.first_name %> <%= @post.user.last_name %></h3>
                <% if policy(@post).edit? %>
                  <%= link_to '<i class="far fa-edit"></i>'.html_safe, edit_post_path(@post), class: "edit-pencil"%>
                  <%= link_to '<i class="far fa-trash-alt"></i>'.html_safe, post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?"}, class: "edit-pencil"%>
                <% end %>
              </div>
              <div class="date-btn">
                <p><strong><%= @post.date.nil? ? "ASAP" : @post.date.strftime("%d %b %Y") %></strong></p>
              </div>
            </div>
            <h4><%= @post.title %></h4>
            <p><%= @post.content %></p>
          </div>
        </div>

    </div>

      <% if current_user == @post.user %>
        <div class="see-offer">
          <p><strong>See your offers to help below</strong></p>
        </div>
      <% elsif @post.bids.any? { |bid| bid.user == current_user} %>
        <div class="see-offer">
          <p><strong>Thanks for offering your help</strong></p>
        </div>
      <% else %>
        <%= link_to post_bids_path(@post), method: :post do %>
          <div class="bid-offer">
            <p><strong>Offer your help</strong></p>
          </div>
        <% end %>
      <% end %>

    <div class="all-bids">

      <% approved = @post.bids.any? { |bid| bid.approved} %>
      <% if approved %>
        <% @post.bids.each do |bid|%>
            <% if bid.approved %>
              <div class="bid">
                <div class="bid-user-info">
                  <% if  bid.user.photo.attached? %>
                    <%= cl_image_tag bid.user.photo.key,height: 40, :quality=>60, crop: :mfit, class: "avatar dropdown-toggle", alt: "profile image", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                  <% else %>
                    <%= cl_image_tag("fpatfvf9edoaaqhbkfrt", width: 40, crop: :fill, class: "avatar", alt: "profile image", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false ) %>
                  <% end %>
                  <h3><%= bid.user.first_name %> <%= bid.user.last_name %></h3>
                </div>
                <div class="view-approve">
                  <%= link_to user_path(bid.user) do %>
                    <div class="view">
                      <p><strong>View Profile</strong></p>
                    </div>
                  <% end %>
                    <div class="approved">
                      <p><strong>Approved!</strong></p>
                    </div>
                </div>
              </div>
            <% end %>
        <% end %>
      <% elsif policy(@post).update? %>
        <% @post.bids.each do |bid|%>
          <div class="bid">
            <div class="bid-user-info">
              <% if  bid.user.photo.attached? %>
                <%= cl_image_tag bid.user.photo.key,height: 40, :quality=>60, crop: :mfit, class: "avatar dropdown-toggle", alt: "profile image", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% else %>
                <%= cl_image_tag("fpatfvf9edoaaqhbkfrt", width: 40, crop: :fill, class: "avatar", alt: "profile image", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false ) %>
              <% end %>
              <h3><%= bid.user.first_name %> <%= bid.user.last_name %></h3>
            </div>
            <div class="view-approve">
              <% if policy(bid).destroy? %>
                <%= link_to bid_path(bid), method: :delete, data: {confirm: "Are you sure you want to cancel this?"} do %>
                  <div class="cancel">
                    <p><strong>Cancel</strong></p>
                  </div>
                <% end %>
              <% end %>
              <%= link_to user_path(bid.user) do %>
                <div class="view">
                  <p><strong>View Profile</strong></p>
                </div>
              <% end %>
                 <% if policy(@post).update? %>
                    <%= link_to post_bid_path(@post, bid), method: :patch do %>
                      <div class="approve">
                        <p><strong>Approve</strong></p>
                      </div>
                    <% end %>
                 <% else %>
                    <div class="pending">
                      <p><strong>Pending</strong></p>
                    </div>
             <% end %>
            </div>
          </div>
        <% end %>
      <% else %>
        <% my_bids = @post.bids.select { |bid| bid.user == current_user} %>
          <% my_bids.each do |bid|%>
              <div class="bid">
                <div class="bid-user-info">
                  <% if  bid.user.photo.attached? %>
                    <%= cl_image_tag bid.user.photo.key,height: 40, :quality=>60, crop: :mfit, class: "avatar dropdown-toggle", alt: "profile image", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                  <% else %>
                    <%= cl_image_tag("fpatfvf9edoaaqhbkfrt", width: 40, crop: :fill, class: "avatar", alt: "profile image", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false ) %>
                  <% end %>
                  <h3><%= bid.user.first_name %> <%= bid.user.last_name %></h3>
                </div>
                <div class="view-approve">
                  <% if bid.user == current_user%>
                    <%= link_to bid_path(bid), method: :delete, data: {confirm: "Are you sure you want to cancel this?"} do %>
                    <div class="cancel">
                      <p><strong>Cancel</strong></p>
                    </div>
                    <% end %>
                  <% end %>
                  <%= link_to user_path(bid.user) do %>
                    <div class="view">
                      <p><strong>View Profile</strong></p>
                    </div>
                  <% end %>
                     <% if current_user == @post.user %>
                        <%= link_to post_bid_path(@post, bid), method: :patch do %>
                          <div class="approve">
                            <p><strong>Approve</strong></p>
                          </div>
                        <% end %>
                     <% else %>
                        <div class="pending">
                          <p><strong>Pending</strong></p>
                        </div>
                     <% end %>
                </div>
              </div>
          <% end %>
          <div class="bid-count">
            <% if @post.bids.count == 0 %>
            <% elsif @post.bids.count == 1 %>
              <p><strong><%= @post.bids.count %> person has offered to help</strong></p>
            <% else %>
              <p><strong><%= @post.bids.count %> people have offered to help</strong></p>
            <% end %>
          </div>
        <% end %>
      <% if approved && current_user == @post.user && !@post.completed  %>
        <%= link_to post_path(@post, completed: true), :method => :put do %>
          <div class="completed">
            <p><strong>Mark as completed</strong></p>
          </div>
        <% end %>
      <% end %>
    </div>

  </div>

  <% if @chatroom %>
    <div class="chat-container">
        <div id="chatroomdiv" class="wrapper">
          <div>
            <h1 class="chatroomheader"># <%= @chatroom.name %></h1>
          </div>

          <div id="messages" data-chatroom-id="<%= @chatroom.id %>">
            <% @chatroom.messages.each do |message| %>
              <% if message.user == current_user %>
              <%= render 'messages/message', message: message %>
              <% else %>
            <%= render 'messages/message_received', message: message %>
            <% end %>
            <% end %>
          </div>

          <div class="type">
            <%= simple_form_for [@chatroom, @message] do |f| %>
            <%= f.input :content, label: 'Type your message here:' %>
            <% end %>
          </div>
        </div>
    </div>
    <div class="chat"></div>
  <% else %>
      <div class="chat-container-placeholder">
        <h2>Help will be <br> with you soon!</h2>
        <%= image_tag "helping.png", alt: "illustration of someone asking for help", width: 300 %>
      </div>
  <% end %>
</div>